apiVersion: v1
kind: Pod
metadata:
  name: chat-api
spec:
  containers:
    - image: localhost:5000/chat-api:latest
      name: chat-api
      livenessProbe:
        httpGet:
          path: /health
          port: 8080