apiVersion: v1
kind: ReplicationController
metadata:
  name: chat-api
spec:
  replicas: 3
  selector:
    app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: kubia
        image: localhost:5000/chat-api:latest
        ports:
        - containerPort: 8080