from enum import Enum, unique


@unique
class UserGender(Enum):
    Agender ='Agender'
    Androgyne = 'Androgyne'
    Androgynous = 'Androgynous'
    Bigender = 'Bigender'
    Cis = 'Cis'
    Cisgender = 'Cisgender'
    CisFemale = 'CisFemale'
    CisMale = 'CisMale'
    CisMan = 'CisMan'
    CisWoman = 'CisWoman'
    CisgenderFemale = 'CisgenderFemale'
    CisgenderMale = 'CisgenderMale'
    CisgenderMan = 'CisgenderMan'
    CisgenderWoman = 'CisgenderWoman'
    FemaletoMale = 'FemaletoMale'
    FTM = 'FTM'
    GenderFluid = 'GenderFluid'
    GenderNonconforming = 'GenderNonconforming'
    GenderQuestioning = 'GenderQuestioning'
    GenderVariant = 'GenderVariant'
    Genderqueer = 'Genderqueer'
    Intersex = 'Intersex'
    MaletoFemale = 'MaletoFemale'
    MTF = 'MTF'
    Neither = 'Neither'
    Neutrois = 'Neutrois'
    Nonbinary = 'Nonbinary'
    Other = 'Other'
    Pangender = 'Pangender'
    Trans = 'Trans'
    TransFemale = 'TransFemale'
    TransMale = 'TransMale'
    TransMan = 'TransMan'
    TransPerson = 'TransPerson'
    TransWoman = 'TransWoman'
    Transfeminine = 'Transfeminine'
    Transgender = 'Transgender'
    TransgenderFemale = 'TransgenderFemale'
    TransgenderMale = 'TransgenderMale'
    TransgenderMan = 'TransgenderMan'
    TransgenderPerson = 'TransgenderPerson'
    TransgenderWoman = 'TransgenderWoman'
    Transmasculine = 'Transmasculine'
    Transsexual = 'Transsexual'
    TranssexualFemale = 'TranssexualFemale'
    TranssexualMale = 'TranssexualMale'
    TranssexualMan = 'TranssexualMan'
    TranssexualPerson = 'TranssexualPerson'
    TranssexualWoman = 'TranssexualWoman'
    TwoSpirit = 'TwoSpirit'
